export const start = async () => {
    try {
    } catch (e) {
        console.error(e);
    }
}